CREATE OR REPLACE TRIGGER update_event_budget_trigger
AFTER UPDATE OF NumGuests ON CLIENT
FOR EACH ROW
BEGIN
    UPDATE EVENT
    SET BUDGET = BUDGET + (:NEW.NumGuests) * 
((SELECT orchestraPrice FROM ORCHESTRA WHERE ORCHESTRAID = EVENT.ORCHESTRAID)+
(SELECT PhotographPrice FROM photograph WHERE photographID = EVENT.photographID))
    WHERE EVENTID = (SELECT EVENTID FROM HELPED WHERE ID = :NEW.CLIENTID);
END;
/
